// <auto-generated />
namespace ImageWebAPIs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FourDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FourDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201606250508091_FourDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
